repos:
  - repo: https://github.com/ambv/black
    rev: 21.6b0
    hooks:
      - id: black
        exclude: ^migrations/

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: 'v5.9.1'
    hooks:
      - id: isort
        exclude: ^migrations/